name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-js-linter:
    name: Run Node.js Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Node.js Lint
        run: npm run lint

  run-php-linter:
    name: Run Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up PHP/Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: json, dom, curl, libxml, mbstring

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint --test
